pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Safi-Ahmed-Shariff/AutoML-DevOps.git', branch 'main'
            }
        }
    }

    stages {
        stage ('Build Docker Image') {
            steps {
                script {
                    docker.build('model.trainer', 'docker/')
                }
            }
        }
    }
}