pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/Safi-Ahmed-Shariff/AutoML-DevOps.git'
                    ]]
                ])
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat 'docker build -t model-trainer ./docker'
                }
            }
        }
        stage('Run Model Trainer') {
            steps {
                   bat """
                            docker create --name temp_container model-trainer
                            docker cp temp_container:/tmp/model.pkl docker/model.pkl
                            docker rm temp_container
                        """
            }
        }
        stage('Upload model to S3 bucket') {
            steps {
                script{
                    bat 'python upload_to_s3.py'
                }
            }
        }
    }
}