pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')     // Jenkins credential ID
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key-id') // Jenkins credential ID
        AWS_DEFAULT_REGION = 'us-east-1'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/Safi-Ahmed-Shariff/AutoML-DevOps.git'
                    ]]
                ])
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat 'docker build -t model-trainer ./docker'
                }
            }
        }

        stage('Run Model Trainer') {
            steps {
                script {
                    // Ensure latest CSV file is used
                    def csvFiles = bat(script: 'dir /b /o:-d train-uploader\\uploads\\*.csv', returnStdout: true).trim().split('\r\n')
                    if (csvFiles.length == 0) {
                        error('❌ No CSV file found in uploads directory.')
                    }
                    def latestCsv = csvFiles[0]

                    // Run container and execute training
                    bat """
                        docker run --rm -v "%CD%\\train-uploader\\uploads:/app/uploads" model-trainer ^
                        python train.py "/app/uploads/${latestCsv}"
                    """
                }
            }
        }

        stage('Upload model to S3 bucket') {
            steps {
                script {
                    bat 'python upload_to_s3.py'
                }
            }
        }
    }
}
